name: CI

on:
  push:
    branches: [ main, ci ]
  pull_request:
    branches: [ main, ci ]
  repository_dispatch:

jobs:
  x86_64-linux-gcc:
    runs-on: [self-hosted, linux]
    steps:

      - name: Event Information
        run: |
          echo "Event '${{ github.event.action }}' received from '${{ github.event.client_payload.repository }}'"

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Flutter Channel Rolled
        if: github.event.action == 'channel_roll'
        run: |
          ARCH=x86_64
          OS=linux
          RUNTIME=gcc
          mkdir -p ${{github.workspace}}/build/debug
          pushd ${{github.workspace}}/build/debug
          cmake .. -DTARGET_TRIPLE=${ARCH}-${OS}-${RUNTIME} -DTARGET_ARCH=x64
          echo "Create Debug Packages"
          cmake .. -DCHANNEL=beta -DENGINE_RUNTIME_MODE=debug
          make package -j
          PACKAGE_FILE=`find -iname flutter-engine-*-debug-*-Linux-*.gz -not -path "./_CPack_Packages/*"`
          echo $PACKAGE_FILE
          md5sum $PACKAGE_FILE > ${PACKAGE_FILE}-MD5SUMS.txt
          PACKAGE_FILE=`find -iname flutter-engine-*-debug-*-Linux-*.deb -not -path "./_CPack_Packages/*"`
          echo $PACKAGE_FILE
          md5sum $PACKAGE_FILE > ${PACKAGE_FILE}-MD5SUMS.txt
          PACKAGE_FILE=`find -iname flutter-engine-*-debug-*-Linux-*.rpm -not -path "./_CPack_Packages/*"`
          echo $PACKAGE_FILE
          md5sum $PACKAGE_FILE > ${PACKAGE_FILE}-MD5SUMS.txt
          popd
          mkdir -p ${{github.workspace}}/build/release
          pushd ${{github.workspace}}/build/release
          echo "Create Release Packages"
          cmake .. -DCHANNEL=beta -DENGINE_RUNTIME_MODE=release
          make package -j
          PACKAGE_FILE=`find -iname flutter-engine-*-debug-*-Linux-*.gz -not -path "./_CPack_Packages/*"`
          echo $PACKAGE_FILE
          md5sum $PACKAGE_FILE > ${PACKAGE_FILE}-MD5SUMS.txt
          PACKAGE_FILE=`find -iname flutter-engine-*-debug-*-Linux-*.deb -not -path "./_CPack_Packages/*"`
          echo $PACKAGE_FILE
          md5sum $PACKAGE_FILE > ${PACKAGE_FILE}-MD5SUMS.txt
          PACKAGE_FILE=`find -iname flutter-engine-*-debug-*-Linux-*.rpm -not -path "./_CPack_Packages/*"`
          echo $PACKAGE_FILE
          md5sum $PACKAGE_FILE > ${PACKAGE_FILE}-MD5SUMS.txt
          popd
          mkdir -p ${{github.workspace}}/build/profile
          pushd ${{github.workspace}}/build/profile
          echo "Create Profile Packages"
          cmake .. -DCHANNEL=beta -DENGINE_RUNTIME_MODE=profile
          make package -j
          PACKAGE_FILE=`find -iname flutter-engine-*-debug-*-Linux-*.gz -not -path "./_CPack_Packages/*"`
          echo $PACKAGE_FILE
          md5sum $PACKAGE_FILE > ${PACKAGE_FILE}-MD5SUMS.txt
          PACKAGE_FILE=`find -iname flutter-engine-*-debug-*-Linux-*.deb -not -path "./_CPack_Packages/*"`
          echo $PACKAGE_FILE
          md5sum $PACKAGE_FILE > ${PACKAGE_FILE}-MD5SUMS.txt
          PACKAGE_FILE=`find -iname flutter-engine-*-debug-*-Linux-*.rpm -not -path "./_CPack_Packages/*"`
          echo $PACKAGE_FILE
          md5sum $PACKAGE_FILE > ${PACKAGE_FILE}-MD5SUMS.txt
          popd

      - name: Build
        run: |
          ARCH=x86_64
          OS=linux
          RUNTIME=gcc
          mkdir -p ${{github.workspace}}/build/debug
          pushd ${{github.workspace}}/build/debug
          cmake .. -DTARGET_TRIPLE=${ARCH}-${OS}-${RUNTIME} -DTARGET_ARCH=x64
          echo "Create Debug Packages"
          cmake .. -DCHANNEL=beta -DENGINE_RUNTIME_MODE=debug
          make package -j
          PACKAGE_FILE=`find -iname flutter-engine-*-debug-*-Linux-*.gz -not -path "./_CPack_Packages/*"`
          echo $PACKAGE_FILE
          md5sum $PACKAGE_FILE > ${PACKAGE_FILE}-MD5SUMS.txt
          PACKAGE_FILE=`find -iname flutter-engine-*-debug-*-Linux-*.deb -not -path "./_CPack_Packages/*"`
          echo $PACKAGE_FILE
          md5sum $PACKAGE_FILE > ${PACKAGE_FILE}-MD5SUMS.txt
          PACKAGE_FILE=`find -iname flutter-engine-*-debug-*-Linux-*.rpm -not -path "./_CPack_Packages/*"`
          echo $PACKAGE_FILE
          md5sum $PACKAGE_FILE > ${PACKAGE_FILE}-MD5SUMS.txt
          popd
          mkdir -p ${{github.workspace}}/build/release
          pushd ${{github.workspace}}/build/release
          echo "Create Release Packages"
          cmake .. -DCHANNEL=beta -DENGINE_RUNTIME_MODE=release
          make package -j
          PACKAGE_FILE=`find -iname flutter-engine-*-debug-*-Linux-*.gz -not -path "./_CPack_Packages/*"`
          echo $PACKAGE_FILE
          md5sum $PACKAGE_FILE > ${PACKAGE_FILE}-MD5SUMS.txt
          PACKAGE_FILE=`find -iname flutter-engine-*-debug-*-Linux-*.deb -not -path "./_CPack_Packages/*"`
          echo $PACKAGE_FILE
          md5sum $PACKAGE_FILE > ${PACKAGE_FILE}-MD5SUMS.txt
          PACKAGE_FILE=`find -iname flutter-engine-*-debug-*-Linux-*.rpm -not -path "./_CPack_Packages/*"`
          echo $PACKAGE_FILE
          md5sum $PACKAGE_FILE > ${PACKAGE_FILE}-MD5SUMS.txt
          popd
          mkdir -p ${{github.workspace}}/build/profile
          pushd ${{github.workspace}}/build/profile
          echo "Create Profile Packages"
          cmake .. -DCHANNEL=beta -DENGINE_RUNTIME_MODE=profile
          make package -j
          PACKAGE_FILE=`find -iname flutter-engine-*-debug-*-Linux-*.gz -not -path "./_CPack_Packages/*"`
          echo $PACKAGE_FILE
          md5sum $PACKAGE_FILE > ${PACKAGE_FILE}-MD5SUMS.txt
          PACKAGE_FILE=`find -iname flutter-engine-*-debug-*-Linux-*.deb -not -path "./_CPack_Packages/*"`
          echo $PACKAGE_FILE
          md5sum $PACKAGE_FILE > ${PACKAGE_FILE}-MD5SUMS.txt
          PACKAGE_FILE=`find -iname flutter-engine-*-debug-*-Linux-*.rpm -not -path "./_CPack_Packages/*"`
          echo $PACKAGE_FILE
          md5sum $PACKAGE_FILE > ${PACKAGE_FILE}-MD5SUMS.txt
          popd

      - name: Runtime Debug artifacts TGZ
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ENGINE_VERSION_DEBUG }}.x86_64-linux-gcc.debug
          path: |
            build/debug/*.tar.gz
            build/debug/*.tar.gz-MD5SUMS.txt

      - name: Runtime Release artifacts TGZ
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ENGINE_VERSION_RELEASE }}.x86_64-linux-gcc.release
          path: |
            build/release/*.tar.gz
            build/release/*.tar.gz-MD5SUMS.txt

      - name: Runtime Profile artifacts TGZ
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ENGINE_VERSION_PROFILE }}.x86_64-linux-gcc.profile
          path: |
            build/profile/*.tar.gz
            build/profile/*.tar.gz-MD5SUMS.txt

      - name: Runtime Debug artifacts Debian
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ENGINE_VERSION_DEBUG }}.x86_64-linux-gcc.debug
          path: |
            build/debug/*.deb
            build/debug/*.deb-MD5SUMS.txt

      - name: Runtime Release artifacts Debian
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ENGINE_VERSION_RELEASE }}.x86_64-linux-gcc.release
          path: |
            build/release/*.deb
            build/release/*.deb-MD5SUMS.txt

      - name: Runtime Profile artifacts Debian
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ENGINE_VERSION_PROFILE }}.x86_64-linux-gcc.profile
          path: |
            build/profile/*.deb
            build/profile/*.deb-MD5SUMS.txt

      - name: Runtime Debug artifacts RPM
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ENGINE_VERSION_DEBUG }}.x86_64-linux-gcc.debug
          path: |
            build/debug/*.rpm
            build/debug/*.rpm-MD5SUMS.txt

      - name: Runtime Release artifacts RPM
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ENGINE_VERSION_RELEASE }}.x86_64-linux-gcc.release
          path: |
            build/release/*.rpm
            build/release/*.rpm-MD5SUMS.txt

      - name: Runtime Profile artifacts RPM
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ENGINE_VERSION_PROFILE }}.x86_64-linux-gcc.profile
          path: |
            build/profile/*.rpm
            build/profile/*.rpm-MD5SUMS.txt
